# Generated by Django 5.2.17 on 2026-09-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_productproperty_catalog_pro_name_76f946_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(help_text='Рекомендуется 1920×600 для верхнего слайдера', upload_to='banners/', verbose_name='Изображение')),
                ('image_mobile', models.ImageField(blank=True, help_text='Необязательно. Показывается на экранах < 768px.', null=True, upload_to='banners/', verbose_name='Изображение (мобильное)')),
                ('link', models.URLField(blank=True, help_text='Используется, если не выбраны категория или товар', verbose_name='Внешняя ссылка')),
                ('position', models.CharField(choices=[('home_top', 'Главная — верхний слайдер'), ('home_middle', 'Главная — середина'), ('category_top', 'Категория — верх'), ('sidebar', 'Боковая колонка')], default='home_top', max_length=30, verbose_name='Позиция')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше — тем раньше в слайдере', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец показа')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Показов')),
                ('clicks_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Кликов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.category', verbose_name='Категория')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
