# Generated by Django 5.2.17 on 2026-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(help_text='Рекомендуется 1920×600 для верхнего слайдера', upload_to='slider/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Необязательно. Показывается на экранах < 768px.', null=True, upload_to='slider/', verbose_name='Изображение (мобильное)'),
        ),
    ]
