# Generated by Django 5.2.17 on 2026-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0008_productproperty_catalog_pro_name_76f946_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Картинка для страницы акции', null=True, upload_to='promotions/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('categories', models.ManyToManyField(blank=True, help_text='Все товары из этих категорий попадут в акцию', related_name='promotions', to='catalog.category', verbose_name='Категории')),
                ('products', models.ManyToManyField(blank=True, help_text='Эти товары добавятся сверх категорий', related_name='promotions', to='catalog.product', verbose_name='Отдельные товары')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
