# Generated by Django 5.2.17 on 2026-09-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('', 'Не указан')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='user',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация'),
        ),
    ]
