# Generated by Django 5.2.17 on 2026-09-09 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_birth_date_user_gender_user_inn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основная организация')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=13, verbose_name='ОГРН')),
                ('address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='Директор')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Банк')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('corr_account', models.CharField(blank=True, max_length=20, verbose_name='Корр. счёт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
