# Generated by Django 5.2.17 on 2026-09-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_address_remove_user_inn_remove_user_kpp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
