# Generated by Django 5.2.17 on 2026-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('ooo', 'ООО'), ('ip', 'ИП')], default='ooo', max_length=3, verbose_name='Тип организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, verbose_name='ОГРН / ОГРНИП'),
        ),
    ]
