# Generated by Django 5.2.17 on 2026-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_organization_org_type_alter_organization_ogrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_representative',
            field=models.BooleanField(default=False, verbose_name='Представитель юрлица'),
        ),
    ]
