# Generated by Django 5.2.17 on 2026-09-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_agree_to_terms_user_agreed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company_representative',
        ),
    ]
