# Generated by Django 5.2.17 on 2026-09-15 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0009_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('notified', models.BooleanField(default=False, verbose_name='Уведомлён')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата уведомления')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notifications', to='catalog.product', verbose_name='Товар')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на поступление',
                'verbose_name_plural': 'Подписки на поступление',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'product')},
            },
        ),
    ]
