# Generated by Django 5.2.17 on 2026-09-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='PRO-инструмент', max_length=255, verbose_name='Название сайта')),
                ('site_description', models.TextField(blank=True, help_text='Для SEO — meta description по умолчанию', max_length=500, verbose_name='Описание сайта')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('admin_email', models.EmailField(blank=True, help_text='Куда приходят уведомления о заказах и заявках', max_length=254, verbose_name='Email для уведомлений')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('work_hours', models.CharField(blank=True, max_length=255, verbose_name='Часы работы')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('vk_url', models.URLField(blank=True, verbose_name='ВКонтакте')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Логотип')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
