# Generated by Django 5.2.17 on 2026-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.FileField(blank=True, help_text='Загрузите сертификат или декларацию соответствия (PDF, JPG, PNG)', null=True, upload_to='certificates/', verbose_name='Сертификат соответствия'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='Ссылка на запись в реестре Росаккредитации (если есть)', max_length=500, verbose_name='Ссылка на реестр'),
        ),
        migrations.AddField(
            model_name='product',
            name='no_certificate_required',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар не подлежит обязательной сертификации', verbose_name='Не подлежит сертификации'),
        ),
    ]
