# Generated by Django 5.2.17 on 2026-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fa-folder-open', help_text='Выберите иконку из Font Awesome: fa-drill, fa-hammer, fa-saw, fa-tools и т.д.', max_length=50, verbose_name='Иконка (Font Awesome)'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для категории (рекомендуемый размер: 400x400)', null=True, upload_to='categories/', verbose_name='Изображение категории'),
        ),
    ]
