# Generated by Django 5.2.17 on 2026-09-16 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_certificate_product_certificate_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='certificate_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='no_certificate_required',
        ),
        migrations.CreateModel(
            name='ProductCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Сертификат соответствия», «Декларация соответствия»', max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(blank=True, help_text='PDF, JPG или PNG', null=True, upload_to='certificates/', verbose_name='Файл')),
                ('url', models.URLField(blank=True, help_text='Ссылка на запись в реестре Росаккредитации', max_length=500, verbose_name='Ссылка на реестр')),
                ('number', models.CharField(blank=True, help_text='Номер сертификата или декларации (если известен)', max_length=100, verbose_name='Номер документа')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Сертификат товара',
                'verbose_name_plural': 'Сертификаты товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
