# Generated by Django 5.2.17 on 2026-09-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_certificate_required',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар не подлежит обязательной сертификации', verbose_name='Не подлежит сертификации'),
        ),
    ]
