# Generated by Django 5.2.17 on 2026-09-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_url_product_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Рекомендуемый размер: 800x800', null=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', verbose_name='Изображение'),
        ),
    ]
