# Generated by Django 5.2.17 on 2026-09-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productproperty',
            index=models.Index(fields=['name', 'value'], name='catalog_pro_name_76f946_idx'),
        ),
    ]
