# Generated by Django 5.2.17 on 2026-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productproperty_catalog_pro_name_76f946_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bento_order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше — тем раньше. Только для категорий с галочкой выше.', verbose_name='Порядок в bento'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_bento',
            field=models.BooleanField(default=False, help_text='Отметьте до 6 категорий для сетки карточек на главной. Если отметить больше — покажутся первые 6 по порядку.', verbose_name='Показывать в bento на главной'),
        ),
    ]
