# Generated by Django 5.2.17 on 2026-09-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_bento_order_category_show_in_bento'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bento_image',
            field=models.ImageField(blank=True, help_text='Отдельная картинка для bento-сетки на главной. Размер зависит от позиции: большая — 468×185, маленькая — 224×185. Если не загружена — используется основная.', null=True, upload_to='bento/', verbose_name='Изображение для bento'),
        ),
    ]
