# Generated by Django 5.2.17 on 2026-10-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_category_bento_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, db_index=True, help_text='Заполняется автоматически при импорте. Показывается только если не загружено своё изображение.', max_length=1000, verbose_name='Ссылка на изображение у поставщика'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, db_index=True, max_length=1000, verbose_name='Ссылка на изображение у поставщика'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Изображение'),
        ),
    ]
