# Generated by Django 5.2.17 on 2026-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Краткое описание способа доставки (показывается клиенту)', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='0 = бесплатно. Если стоимость рассчитывается индивидуально — оставьте 0 и напишите в описании', max_digits=10, verbose_name='Стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Способ доставки',
                'verbose_name_plural': 'Способы доставки',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
