# Generated by Django 5.2.17 on 2026-09-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_deliverymethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method_name',
            field=models.CharField(blank=True, help_text='Сохраняется на момент оформления заказа', max_length=255, verbose_name='Способ доставки (снимок)'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverymethod', verbose_name='Способ доставки'),
        ),
    ]
